### ISSUE TITLE
您这个真的对吗

### ISSUE THREAD

**Issue by ghost** [ouuan/segmentTree#1]
我怎么感觉您在处理区间查询时出了一点问题啊。

您是懒标记下传，那么在 pushdown 时为什么没有更新 cur 的 val 啊。

难道是我理解错了？

**Comment by ouuan** [comment]
我们写法不一样？

**Comment by ghost** [comment]
您数据过得了吗

**Comment by ouuan** [comment]
我好像听说过有 pushdown 时更新当前节点和 pushdown 时更新两个儿子这两种不同的写法。

**Comment by ghost** [comment]
不是还有标记永久化吗

**Comment by ouuan** [comment]
> 不是还有标记永久化吗

我说过没有吗..

**Comment by ouuan** [comment]
> 您数据过得了吗

过不了的话我早就会发现了..
